### ISSUE TITLE
Clojure examples fail with ClassNotFoundException

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [HumbleUI/Skija#25]
On a fresh clone & local build:
```
$ cd examples/clojure && ./scripts/run.py
Syntax error (ClassNotFoundException) compiling at (lwjgl/main.clj:1:1).
io.github.humbleui.types.Rect

Full report at:
/tmp/clojure-1209162283782155536.edn

Traceback (most recent call last):
  File "/home/w1n5t0n/dev/lib/skija/examples/clojure/./script/run.py", line 11, in <module>
    sys.exit(main())
  File "/home/w1n5t0n/dev/lib/skija/examples/clojure/./script/run.py", line 7, in main
    subprocess.check_call(["clj", "-M:" + system, "-m", "lwjgl.main"])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['clj', '-M:linux', '-m', 'lwjgl.main']' returned non-zero exit status 1.
```

Same for `clojure-snake`.

Full report: https://pastebin.com/MGzbjChf

`bitmap`, `jwm`, and `swt` demos seem to work, others also fail but for different reasons.

**Comment by monkey-w1n5t0n** [comment]
Perfect, thanks! Now I can start playing around :)

**Comment by tonsky** [comment]
BTW if you need Clojure, take a look at https://github.com/HumbleUI/HumbleUI. It has some Clojure binding for both Skija and JWM for window creation.
